language: java

addons:
  sonarcloud:
    organization: "pjvilloud-github"

script:
   # other script steps might be done before running the actual analysis
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar; fi'
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io
